name: uda
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11.*
  - albumentations=1.3.*
  - pytorch=2.1.*
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0=cuda
  - torchmetrics=1.2.*
  - torchvision=0.16.*
  - opencv=4.7.*
  - py-opencv=4.7.*
  - pandas=2.1.*
  - numpy=1.24.*
  - tqdm=4.66.*
  - pdf2image=1.16.*
  - pip:
      - tensorflow==2.15.*
